# Generated by Django 4.2.2 on 2023-06-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='phone_number',
            field=models.IntegerField(default=False),
        ),
    ]
