# Generated by Django 4.1.7 on 2023-06-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_custom_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
