# Generated by Django 4.1.7 on 2023-06-28 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.variant')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.custom_user')),
            ],
        ),
    ]
