# Generated by Django 4.1.7 on 2023-06-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_user_management'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_management',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
