# Generated by Django 4.1.7 on 2023-06-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_variant',
            new_name='variant',
        ),
    ]
