# Generated by Django 4.1.7 on 2023-06-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
