# Generated by Django 4.1.7 on 2023-07-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_orderitems_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
