# Generated by Django 4.1.7 on 2023-07-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_orderitems_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.custom_user')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.variant')),
            ],
        ),
    ]
