# Generated by Django 4.1.7 on 2023-07-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_wishist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishist',
            new_name='Wishlist',
        ),
    ]
