# Generated by Django 4.1.7 on 2023-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum',
            field=models.FloatField(default=0),
        ),
    ]
