# Generated by Django 4.1.7 on 2023-07-31 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_order_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_cancelled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_cancelled',
        ),
    ]
