# Generated by Django 4.1.7 on 2023-08-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_order_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_deleted',
        ),
    ]
