# Generated by Django 4.1.7 on 2023-08-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_remove_order_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='image1_variants',
            field=models.ManyToManyField(blank=True, related_name='image1_variants', to='app1.variant'),
        ),
        migrations.AddField(
            model_name='variant',
            name='image2_variants',
            field=models.ManyToManyField(blank=True, related_name='image2_variants', to='app1.variant'),
        ),
    ]
