# Generated by Django 4.1.7 on 2023-08-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.offer'),
        ),
    ]
